var list = {
  animals: [
    {
      title: "Vaquite",
      link: "https://go.echoar.xyz/FC84",
      left: 10,
      longlat: [26.73, -110.71],
      foundin: ["Northern part of Gulf of Mexico"],
    },
    {
      title: "Asian Elephants",
      link: "https://go.echoar.xyz/ggvd",
      left: 50000,
      longlat: [8.03, 80.82],
      foundin: [
        "Minneriya National Park Sri Lanka",
        "Nagarhole Reserves Karnataka,India",
        "Sumatra,Indonesia",
      ],
    },
    {
      title: "Snow Leopard",
      link: "https://go.echoar.xyz/wb5y",
      left: 6590,
      longlat: [43.66, 101.52],
      foundin: [
        "Gobi Gurvansaikhan National Park,Mongolia",
        " Jigme Dorji National Park,Bhutan",
        "Shey-Phoksundo National Park, Nepal",
        "Hemis National Park.India",
      ],
    },
    {
      title: "Gorilla",
      link: "https://go.echoar.xyz/v1Da",
      left: 1063,
      longlat: [-1.4, 29.56],
      foundin: [
        "Volcanoes National Park,Rwanda",
        "Mgahinga National Park,Uganda",
        "Virunga National Park,Congo",
        " Bwindi Impenetrable National Park,Uganda",
      ],
    },
    {
      title: "Javan Rhinoceros",
      link: "https://go.echoar.xyz/iHpJ",
      left: 68,
      longlat: [-6.78, 105.37],
      foundin: ["Ujung Kulon National Park,Indonesia"],
    },
    {
      title: "Irrawaddy Dolphins",
      link: "https://go.echoar.xyz/DsgN",
      left: 100,
      longlat: [15.51, 95.14],
      foundin: ["Ayeyarwady River, Myanmar", "Mahakam River, Indonesian"],
    },
    {
      title: "Giant Panda",
      link: "https://go.echoar.xyz/RsqR",
      left: 1864,
      longlat: [29, 106],
      foundin: ["South-West, China"],
    },
    {
      title: "Tiger",
      link: "https://go.echoar.xyz/gKne",
      left: 3900,
      longlat: [23.41, 80.57],
      foundin: [
        "Bandhavgarh National Park,India",
        "Ranthambore National Park,Rajasthan",
        "Sundarbans and the Chittagong Hill, Bangladesh",
        "South China",
        "Sumatra",
        "Siberia",
        "Nepal",
      ],
    },
    {
      title: "Whooping Crane",
      link: "https://go.echoar.xyz/4Mph",
      left: 505,
      longlat: [39.32, -111.09],
      foundin: ["North-America", "Central Mexico", "Utah"],
    },
    // {
    //   title: "Tasmanian Devil",
    //   link: "https://go.echoar.xyz/w8P3",
    //   left: 10000,
    //   longlat:[36.6, -121.89],
    //   foundin: ["Tasmania"],
    // },
    {
      title: "Blue Whale",
      link: "https://go.echoar.xyz/WpLu",
      left: 24000,
      longlat: [36.6, -121.89],
      foundin: [
        "Gulf of St. Lawrence",
        "Coast of Monterey",
        "baja California,Mexico",
      ],
    },
  ],
  plants: [
    {
      title: "Texas Wild rice",
      link: "https://go.echoar.xyz/mXoB",
      longlat: [29.8, -97.94],
      foundin: ["San Macros"],
    },
    {
      title: "Western Prairie Orchid",
      link: "https://go.echoar.xyz/gtwc",
      longlat: [53.76, -98.81],
      foundin: [
        "Manitoba",
        "Canada",
        "Minnesota",
        "North Dakota",
        "Iowa",
        "Missouri",
        "Nebraska",
        "Kansas",
      ],
    },
    {
      title: "Rafflesia",
      link: "https://go.echoar.xyz/onHi",
      longlat: [0.96, 114.55],
      foundin: ["Borneo", "Sumatra"],
    },
  ],
};
